# Generated by Django 2.2 on 2021-09-03 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwarePlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Аппаратная платформа')),
            ],
            options={
                'verbose_name': 'Аппаратная платформа',
                'verbose_name_plural': 'Аппаратные платформы',
            },
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Модификация исполненеия')),
            ],
            options={
                'verbose_name': 'Модификация исполненеия',
                'verbose_name_plural': 'Модификации исполненеий',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=35, verbose_name='Номер сети')),
            ],
            options={
                'verbose_name': 'Защищенная сеть',
                'verbose_name_plural': 'Защищенные сети',
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название узла')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата введения в эксплуатацию')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Местоположение')),
                ('vipnet_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Идентификатор в сети')),
                ('serial_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Серийный номер')),
                ('account_number_skzi', models.CharField(blank=True, max_length=25, null=True, verbose_name='Учетный номер СКЗИ')),
                ('account_number_fstec', models.CharField(blank=True, max_length=25, null=True, verbose_name='Учетный номер ФСТЭК')),
                ('hardware_platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.HardwarePlatform', verbose_name='Аппаратная платформа')),
                ('modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Modification', verbose_name='Модификация исполненеия')),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coord', to='inventory.Network', verbose_name='Защищенная сеть')),
            ],
            options={
                'verbose_name': 'Координатор',
                'verbose_name_plural': 'Координаторы',
            },
        ),
    ]
