# Generated by Django 2.2 on 2021-09-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardwareplatform',
            options={'ordering': ['-name'], 'verbose_name': 'Аппаратная платформа', 'verbose_name_plural': 'Аппаратные платформы'},
        ),
        migrations.AlterModelOptions(
            name='modification',
            options={'ordering': ['-name'], 'verbose_name': 'Модификация исполненеия', 'verbose_name_plural': 'Модификации исполненеий'},
        ),
    ]
