# Generated by Django 2.2 on 2020-12-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='org_city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='org_state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
