# Generated by Django 2.2 on 2021-07-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройства'},
        ),
        migrations.AlterModelOptions(
            name='distributor',
            options={'verbose_name': 'Дистрибьютор', 'verbose_name_plural': 'Дистрибьюторы'},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': 'Лицензия', 'verbose_name_plural': 'Лицензии'},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name': 'Защищенная сеть', 'verbose_name_plural': 'Защищенные сети'},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='vpn',
            options={'verbose_name': 'Дистрибутив ключей', 'verbose_name_plural': 'Дистрибутивы ключей'},
        ),
        migrations.AlterField(
            model_name='license',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='short_name',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Сокращенное название'),
        ),
    ]
