# Generated by Django 2.2 on 2021-07-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210728_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpn',
            name='reg_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Рег. номер СКИ'),
        ),
    ]
