# Generated by Django 2.2 on 2020-12-01 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201201_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=6)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('reg_organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_orgs', to='events.Organisation')),
            ],
        ),
    ]
