# Generated by Django 2.2 on 2020-12-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_reglament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglament',
            name='reg_date',
            field=models.DateField(),
        ),
    ]
