# Generated by Django 2.2 on 2021-08-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210730_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['-reg_number'], 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='vpn',
            options={'ordering': ['-reg_date'], 'verbose_name': 'Дистрибутив ключей', 'verbose_name_plural': 'Дистрибутивы ключей'},
        ),
        migrations.AddField(
            model_name='vpn',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
