# Generated by Django 2.2 on 2021-08-04 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210802_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributors', to='events.Distributor', verbose_name='Распространитель'),
        ),
    ]
