# Generated by Django 2.2 on 2020-12-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20201201_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglament',
            name='reg_number',
            field=models.CharField(max_length=6, verbose_name='Регистрационный номер'),
        ),
    ]
