# Generated by Django 2.2 on 2020-12-01 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20201201_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='org_address',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Физический адрес'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_contact_employee',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ответственный за СКЗИ'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_inn',
            field=models.CharField(max_length=6, verbose_name='ИНН организации'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_name',
            field=models.CharField(max_length=120, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_state',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Муниципальный район/округ'),
        ),
        migrations.AlterField(
            model_name='reglament',
            name='reg_date',
            field=models.DateField(verbose_name='Дата присоединения'),
        ),
        migrations.AlterField(
            model_name='reglament',
            name='reg_organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_orgs', to='events.Organisation', verbose_name='Организация'),
        ),
    ]
