# Generated by Django 2.2 on 2021-08-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210804_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='device_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ID устройства'),
        ),
    ]
