# Generated by Django 2.2.9 on 2020-12-17 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20201201_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=35, verbose_name='Организация дистрибьютора')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Местоположение')),
            ],
        ),
        migrations.CreateModel(
            name='KeyDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=35, verbose_name='Организация дистрибьютора')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_license', models.CharField(max_length=20, verbose_name='Номер акта П/П')),
                ('lic_date', models.DateField(blank=True, null=True, verbose_name='Дата акта')),
                ('ammount', models.IntegerField(blank=True, null=True, verbose_name='Количество лицензий')),
                ('distrib_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distruitors', to='events.Distributor', verbose_name='Распространитель')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys_date', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(blank=True, max_length=30, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('device_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='events.KeyDevice')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license', to='events.KeyDevice')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_numbers', to='events.Organisation')),
            ],
        ),
    ]
