# Generated by Django 2.2.9 on 2020-12-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_distributor_event_keydevice_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keydevice',
            name='type',
            field=models.CharField(max_length=35, verbose_name='Тип носителя'),
        ),
    ]
