# Generated by Django 2.2.9 on 2020-12-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20201217_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='device_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Серийный номер устройства'),
        ),
        migrations.AlterField(
            model_name='event',
            name='device_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='events.KeyDevice', verbose_name='СКИ записана на'),
        ),
        migrations.AlterField(
            model_name='event',
            name='keys_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи СКИ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license', to='events.License', verbose_name='Акт П/П'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_numbers', to='events.Organisation', verbose_name='Организация'),
        ),
    ]
