# Generated by Django 2.2.9 on 2020-12-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20201217_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='keys_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рег. номер СКИ'),
        ),
    ]
