# Generated by Django 2.2.9 on 2020-12-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_keys_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='keys_date',
            field=models.DateTimeField(verbose_name='Дата выдачи СКИ'),
        ),
    ]
