# Generated by Django 2.2.9 on 2020-12-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20201217_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='keys_date',
            field=models.DateField(verbose_name='Дата выдачи СКИ'),
        ),
    ]
