# Generated by Django 2.2 on 2021-03-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_vpn_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='reglament',
            name='reg_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата присоединения'),
        ),
        migrations.AlterField(
            model_name='reglament',
            name='reg_number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Регистрационный номер'),
        ),
    ]
