# Generated by Django 2.2 on 2021-03-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20210329_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='org_inn',
            field=models.CharField(max_length=10, verbose_name='ИНН организации'),
        ),
        migrations.AlterField(
            model_name='reglament',
            name='reg_number',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Регистрационный номер'),
        ),
    ]
